default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch("RAILS_TIMEOUT") { 5000 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL"){ "default" }.gsub('?', '_development?') %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL"){ "default" }.gsub('?', '_test?') %>

staging:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL"){ "default" }.gsub('?', '_staging?') %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL"){ "default" }.gsub('?', '_production?') %>
